const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
let voices=[],queue=[],qIndex=0,currentText='',currentOffset=0,playing=false,paused=false,finished=false,utteranceVersion=0,ctx=null,musicGain=null,musicTimers=[],musicOsc=[];
const maleVoice=v=>/\b(male|masculin[oa]|hombre|david|jorge|pablo|diego|carlos|juan|miguel|andres|andrés|luis|antonio|enrique|alex|alejandro|raul|raúl|jorge)\b/i.test(v.name);
const voiceAllowed=v=>/^es([_-]|$)/i.test(v.lang);
function getVoices(){voices=speechSynthesis.getVoices().filter(voiceAllowed);const sel=$('#voice');if(!sel)return;const old=sel.value;sel.innerHTML='<option value="auto">Automática · español latino</option>';voices.forEach((v,i)=>{const opt=document.createElement('option');opt.value=String(i);opt.textContent=(maleVoice(v)?'Masculina · ':'')+v.name+' · '+v.lang;sel.appendChild(opt)});if(old!=='auto'&&Number.isInteger(Number(old))&&voices[Number(old)])sel.value=old}
getVoices();speechSynthesis.onvoiceschanged=getVoices;
function selectedVoice(){const v=$('#voice')?.value;if(v&&v!=='auto'&&voices[Number(v)])return voices[Number(v)];return voices.find(x=>/^es[-_]419$/i.test(x.lang))||voices.find(x=>/^es[-_]US$/i.test(x.lang))||voices[0]||null}
function selectedPitch(){const style=$('#narration')?.value||'natural';return style==='serene'?0.92:style==='warm'?1.04:style==='bright'?1.1:1}
function updatePlayButtons(){if($('#play'))$('#play').textContent=finished?'↻ Reproducir de nuevo':playing&&!paused?'▶ Reproduciendo':'▶ Reproducir capítulo';if($('#pause'))$('#pause').disabled=!playing||paused||finished;if($('#resume'))$('#resume').disabled=!paused}
function makeQueue(){queue=$$('.leaf p').map(p=>p.textContent.trim()).filter(Boolean);qIndex=0;currentText='';currentOffset=0;finished=false}
function speakCurrent(offset=0,keepPaused=false){if(!currentText)return;const version=++utteranceVersion;const u=new SpeechSynthesisUtterance(currentText.slice(offset));u.lang=selectedVoice()?.lang||'es-419';u.voice=selectedVoice();u.rate=Number($('#rate')?.value||'.94');u.pitch=selectedPitch();u.onboundary=e=>{if(version===utteranceVersion&&Number.isFinite(e.charIndex))currentOffset=offset+e.charIndex};u.onend=()=>{if(version!==utteranceVersion||paused)return;currentOffset=currentText.length;nextParagraph()};u.onerror=()=>{if(version===utteranceVersion&&!paused)nextParagraph()};speechSynthesis.speak(u);if(keepPaused)speechSynthesis.pause()}
function nextParagraph(){if(!playing||paused)return;if(qIndex>=queue.length){playing=false;paused=false;finished=true;updatePlayButtons();return}currentText=queue[qIndex++];currentOffset=0;speakCurrent(0,false)}
function playChapter(){if(finished||!queue.length)makeQueue();if(paused){resumeChapter();return}if(!playing){playing=true;paused=false;updatePlayButtons();if(!currentText)nextParagraph();else speakCurrent(currentOffset,false)}}
function pauseChapter(){if(!playing||paused)return;speechSynthesis.pause();paused=true;updatePlayButtons()}
function resumeChapter(){if(!paused)return;speechSynthesis.resume();paused=false;playing=true;updatePlayButtons()}
function restartChapter(){utteranceVersion++;speechSynthesis.cancel();paused=false;playing=false;finished=false;makeQueue();playChapter()}
$('#play')?.addEventListener('click',()=>finished?restartChapter():!playing?playChapter():paused?resumeChapter():pauseChapter());$('#pause')?.addEventListener('click',pauseChapter);$('#resume')?.addEventListener('click',resumeChapter);$('#stop')?.addEventListener('click',restartChapter);$('#voice-preview')?.addEventListener('click',()=>{const u=new SpeechSynthesisUtterance('Esta es una muestra de la voz seleccionada para el audiolibro.');const v=selectedVoice();u.lang=v?.lang||'es-419';if(v)u.voice=v;u.rate=Number($('#rate')?.value||'.94');u.pitch=selectedPitch();speechSynthesis.speak(u)});
function updateRate(){const slider=$('#rate');if($('#rateval'))$('#rateval').textContent=Number(slider?.value||'.94').toFixed(2)+'×';if(!playing||!currentText||finished)return;const pos=currentOffset;const wasPaused=paused;utteranceVersion++;speechSynthesis.cancel();speakCurrent(pos,wasPaused)}$('#rate')?.addEventListener('input',updateRate);$('#narration')?.addEventListener('change',()=>{if(playing)updateRate()});
const trackRoots={silk:[220,196,174.61,196],garden:[261.63,220,174.61,196],velvet:[196,174.61,146.83,164.81],sea:[174.61,196,220,164.81],dusk:[207.65,185,164.81,138.59],pulse:[146.83,164.81,196,174.61],glass:[246.94,220,196,174.61],ember:[164.81,146.83,130.81,146.83],salon:[196,220,246.94,174.61],dawn:[261.63,293.66,220,246.94]};
function stopMusic(){musicTimers.forEach(clearTimeout);musicTimers=[];musicOsc.forEach(o=>{try{o.stop()}catch{}});musicOsc=[];if(ctx){try{ctx.close()}catch{}ctx=null}musicGain=null}
function playMusic(name){stopMusic();if(name==='off')return;const AC=window.AudioContext||window.webkitAudioContext;if(!AC)return;ctx=new AC();const master=ctx.createGain();master.gain.value=Number($('#music-volume')?.value||'.28');master.connect(ctx.destination);musicGain=master;ctx.resume();const delay=ctx.createDelay(2),fb=ctx.createGain(),wet=ctx.createGain();delay.delayTime.value=.72;fb.gain.value=.22;wet.gain.value=.16;master.connect(delay);delay.connect(fb);fb.connect(delay);delay.connect(wet);wet.connect(ctx.destination);const roots=trackRoots[name]||trackRoots.silk;const minor=['silk','velvet','dusk','ember','salon'].includes(name);let ix=0;function pad(){if(!ctx)return;const now=ctx.currentTime,root=roots[ix++%roots.length],base=[root/2,root,root*(minor?1.2:1.26),root*1.5];const voices=[];base.forEach((freq,n)=>{const osc=ctx.createOscillator(),tone=ctx.createOscillator(),filter=ctx.createBiquadFilter(),env=ctx.createGain(),pan=ctx.createStereoPanner();osc.type=n===0?'triangle':'sine';tone.type='sine';osc.frequency.value=freq;tone.frequency.value=freq*1.003;filter.type='lowpass';filter.frequency.value=520+n*100;filter.Q.value=.35;pan.pan.value=(n-1.5)*.28;env.gain.setValueAtTime(.0001,now);env.gain.exponentialRampToValueAtTime([.035,.023,.018,.012][n],now+9);osc.connect(filter);tone.connect(filter);filter.connect(env);env.connect(pan);pan.connect(master);pan.connect(delay);osc.start(now);tone.start(now);voices.push({osc,tone,env})});musicOsc.push(...voices.flatMap(v=>[v.osc,v.tone]));const fadeAt=now+20;voices.forEach(v=>{v.env.gain.setTargetAtTime(.0001,fadeAt,4);v.osc.stop(fadeAt+18);v.tone.stop(fadeAt+18)});musicTimers.push(setTimeout(()=>{if(ctx)pad()},16000))}pad()}
$('#music')?.addEventListener('change',e=>playMusic(e.target.value));$('#music-volume')?.addEventListener('input',e=>{if(musicGain&&ctx)musicGain.gain.setTargetAtTime(Number(e.target.value),ctx.currentTime,.12)});
let idx=0;const leaves=$$('.leaf');function showLeaf(n,flip=true){if(!leaves.length)return;idx=Math.max(0,Math.min(n,leaves.length-1));leaves.forEach((x,i)=>x.hidden=i!==idx);if($('#leafcount'))$('#leafcount').textContent=`Página ${idx+1} de ${leaves.length}`;if($('#prev'))$('#prev').disabled=idx===0;if($('#next'))$('#next').disabled=idx===leaves.length-1;const bar=$('#progress');if(bar)bar.style.width=((idx+1)/leaves.length*100)+'%';if(flip){const el=leaves[idx];el.classList.add('turn');setTimeout(()=>el.classList.remove('turn'),40)}}$('#prev')?.addEventListener('click',()=>showLeaf(idx-1));$('#next')?.addEventListener('click',()=>showLeaf(idx+1));showLeaf(0,false);updatePlayButtons();